default: &default
  adapter: postgresql

development:
  <<: *default
  database: rails-practice-instance-variables-development

test:
  <<: *default
  database: rails-practice-instance-variables-test
